# Generated by Django 4.0.1 on 2022-01-31 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myusers',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=30)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userPassword', models.CharField(max_length=8)),
            ],
        ),
    ]
